version: '3'

services:
  redis:
    image: redis
    command: redis-server
    volumes: 
      - ./redis-data:/data
    expose: 
      - 6379
  app:
    build: ./
    stdin_open: true 
    tty: true       
    volumes:
      - .:/questionnaire
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

volumes: 
  redis-data: